apiVersion: apps/v1
kind: Deployment
metadata:
 name: helloworld-deployment
 labels: 
  app: helloworld
spec:
 replicas: 1
 selector:
  matchLabels:
   app: helloworld
 template:
  metadata:
   labels:
    app: helloworld
  spec:
   containers:
   - name: helloworld
     image: christianhxc/helloworld:1.0
     ports:
     - containerPort: 80
     resources:
      requests:
       cpu: 50m
      limits:
       cpu: 100m 